import {
  ClerkProvider,
} from '@clerk/nextjs'




import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/app/components/Topbar";
import Navber from "@/app/components/Navber";
import Footer from "@/app/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     <Topbar/>
    //     <Navber/>
    //     {children}
    //     <Footer/>
    //   </body>
    // </html>

<ClerkProvider>
      <html lang="en">
        <body>
          {/* <SignedOut>
            <SignInButton />
          </SignedOut> */}
          {/* <SignedIn>
            <UserButton />
          </SignedIn> */}

          <div className='fixed z-50 w-full'>
          <Topbar/>
          <Navber/>
          </div>
          <div className='p-32
          '>
          {children}
          </div>
          <Footer/>
        </body>
      </html>
    </ClerkProvider>



    
  );
}
